# Generated by Django 2.1.5 on 2019-02-10 16:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('employment_date', models.DateField(verbose_name='Employment date')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=models.SET(app.models.get_chief), related_name='employees', to='app.Profile', verbose_name='Chief')),
            ],
        ),
    ]
